### ISSUE TITLE
Update to 1.x?

### ISSUE THREAD

**Issue by RobGruhl** [trek10inc/serverless-secrets#14]
Any plans to update this to the current version of serverless?

**Comment by goodhanded** [comment]
Bump!

**Comment by fantapop** [comment]
I don't see any references to the _meta directory on the serverless site.  Was this a part of the 0.5.x version of serverless?

**Comment by shortjared** [comment]
Yes. This secrets plugin is pretty much dead. There are potentially better approaches that don't require wrapping and mutation at deploy time like this plugin.
