### ISSUE TITLE
Decryptor registered too early

### ISSUE THREAD

**Issue by silver2k** [trek10inc/serverless-secrets#8]
Hi,

I am trying to use Serverless Secrets with a region other than `us-east-1` (We're not allow to hold sensitive data in the US), however we noticed it just wouldn't work!
Further analysis shows that the generated `_serverless_handler.js` that gets deployed instantiates the decryptors before the envVars are set - so `CREDSTASH_REGION` is alway `us-east-1`

Generated code...

```
'use strict';

var decryptor = require('./serverless-secrets/decryptor');

var envVars = {"SERVERLESS_PROJECT":"....etc
```

:sob:

**Comment by shortjared** [comment]
Merged into master. Have not cut a new release yet though.

**Comment by silver2k** [comment]
Do it. You know you want to... 😀

**Comment by shortjared** [comment]
It's on my todo. Shouldn't take long.
